# Site settings
title: Ubaldo Miramontes Developer
description: Full Stack Dev
# baseurl: "/particle" # the subpath of your site, e.g. /blog
#url: "https://blooming-wave-89594.herokuapp.com/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ubaldo Miramontes
user_description: Full Stack Developer
user_title: Software Developer
email: uba.sk8@gmail.com
twitter_username: uba_sk8
github_username:  Uba_sk8
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
